port 6379
bind 0.0.0.0

protected-mode yes

dir /data

save 900 1
save 300 10
save 60 10000

appendonly yes
appendfsync everysec

maxmemory 512mb
maxmemory-policy allkeys-lru

tcp-keepalive 300
timeout 0

loglevel notice
logfile ""

databases 16

rdbcompression yes
rdbchecksum yes

rename-command FLUSHDB ""
rename-command FLUSHALL ""
rename-command DEBUG ""
