export const SUBSCRIPTION_TIERS = {
  FREE: {
    name: 'Free',
    price: 0,
    features: [
      '1 workspace',
      '100 AI credits/month',
      'Basic transcription',
      '5 saved prompts',
      'Community support',
    ],
    aiCredits: 100,
    maxWorkspaces: 1,
    maxPrompts: 5,
    maxTeamMembers: 0,
    highlighted: false,
  },
  PRO: {
    name: 'Pro',
    price: 20,
    features: [
      'Unlimited workspaces',
      '1,000 AI credits/month',
      'Real-time transcription',
      'Unlimited saved prompts',
      'Screen context awareness',
      'Priority support',
      'Custom AI providers',
    ],
    aiCredits: 1000,
    maxWorkspaces: -1,
    maxPrompts: -1,
    maxTeamMembers: 0,
    highlighted: true,
  },
  TEAM: {
    name: 'Team',
    price: 50,
    features: [
      'Everything in Pro',
      '5,000 AI credits/month',
      'Team workspaces',
      'Shared prompts',
      'Team analytics',
      'Admin controls',
      'Priority support + SLAs',
    ],
    aiCredits: 5000,
    maxWorkspaces: -1,
    maxPrompts: -1,
    maxTeamMembers: 10,
    highlighted: false,
  },
  ENTERPRISE: {
    name: 'Enterprise',
    price: -1,
    features: [
      'Everything in Team',
      'Custom AI credits',
      'Self-hosted option',
      'SSO/SAML',
      'Audit logs',
      'Dedicated support',
      'Custom integrations',
    ],
    aiCredits: -1,
    maxWorkspaces: -1,
    maxPrompts: -1,
    maxTeamMembers: -1,
    highlighted: false,
  },
} as const;

export const AI_CREDIT_COSTS = {
  GPT_4O: { input: 1, output: 2 },
  GPT_4_TURBO: { input: 1, output: 2 },
  GPT_3_5_TURBO: { input: 0.1, output: 0.2 },
  CLAUDE_3_OPUS: { input: 2, output: 4 },
  CLAUDE_3_SONNET: { input: 0.5, output: 1 },
  CLAUDE_3_HAIKU: { input: 0.1, output: 0.2 },
  GEMINI_PRO: { input: 0.1, output: 0.2 },
  GEMINI_ULTRA: { input: 1, output: 2 },
  GROQ_LLAMA3: { input: 0.05, output: 0.1 },
  GROQ_MIXTRAL: { input: 0.1, output: 0.2 },
  OPENROUTER_AUTO: { input: 0.5, output: 1 },
  OLLAMA_CUSTOM: { input: 0, output: 0 },
} as const;
